apiVersion: apps/v1
kind: Deployment
metadata:
  name: iasp540-mysql
spec:
  selector:
    matchLabels:
      app: iasp540-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iasp540-mysql
    spec:
      containers:
        - image: mysql:8.0
          name: iasp540-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: cybersecurity
          ports:
            - containerPort: 3306
              name: iasp540-mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: iasp540-mysql-pv-claim
