apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iasp540-mysql-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
