apiVersion: v1
kind: Service
metadata:
  name: fruitstore-service
spec:
  selector:
    app: fruitstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 #has to match the flask port
  type: ClusterIP
